### ISSUE TITLE
Getting Started can't find boardpath

### ISSUE THREAD

**Issue by kerryeven** [sparkfun/AmbiqSuiteSDK#3]
make works but make bootload ... does not...

Makefile:149: *** Error: BOARDPATH must be provided.  Stop.

Followed Getting Started.  : Details:....

$ YOUR_BOARD=redboard_artemis_nano

kerry@Kerry-pc MINGW64 ~/Documents/AmbiqSuiteSDK/boards_sfe/common/examples/blinky/gcc ((9c31f07...))
$ make BOARD=$YOUR_BOARD
Makefile:112: Using BOARD=redboard_artemis_nano at ../../../../redboard_artemis_nano
Makefile:117: warning: you have not defined COM_PORT. Assuming it is COM4
Makefile:121: warning: you have not defined PYTHON3. assuming it is accessible by 'python3'
Makefile:125: defaulting to 115200 baud for ASB
Makefile:129: defaulting to 921600 baud for SVL
Makefile:134: warning: you have not defined SDKPATH so will continue assuming that the SDK root is at ../../../../..
Makefile:142: warning: you have not defined COMMONPATH so will continue assuming that the COMMON root is at ../../../../common
Makefile:163: warning: you have not defined PROJECTPATH so will continue assuming that the PROJECT root is at ../../../../common/examples/blinky
Makefile:170: CONFIG=../../../../common/examples/blinky/gcc/redboard_artemis_nano/bin
 Compiling gcc ../../../../common/examples/blinky/main.c
 Compiling gcc ../../../../common/tools_sfe/templates/startup_gcc.c
 Compiling gcc ../../../../../utils/am_util_delay.c
 Compiling gcc ../../../../../utils/am_util_faultisr.c
 Compiling gcc ../../../../../utils/am_util_stdio.c
 Compiling gcc ../../../../../devices/am_devices_led.c
 Linking gcc ../../../../common/examples/blinky/gcc/redboard_artemis_nano/bin/blinky_asb.axf with script ../../../../common/tools_sfe/templates/asb_linker.ld
 Copying gcc ../../../../common/examples/blinky/gcc/redboard_artemis_nano/bin/blinky_asb.bin...

kerry@Kerry-pc MINGW64 ~/Documents/AmbiqSuiteSDK/boards_sfe/common/examples/blinky/gcc ((9c31f07...))
$ make $YOUR_BOARD bootload_asb
Makefile:109: warning: no BOARD specified, will fall back to BOARDPATH for arbitrary bsp locations
Makefile:117: warning: you have not defined COM_PORT. Assuming it is COM4
Makefile:121: warning: you have not defined PYTHON3. assuming it is accessible by 'python3'
Makefile:125: defaulting to 115200 baud for ASB
Makefile:129: defaulting to 921600 baud for SVL
Makefile:134: warning: you have not defined SDKPATH so will continue assuming that the SDK root is at ../../../../..
Makefile:142: warning: you have not defined COMMONPATH so will continue assuming that the COMMON root is at ../../../../common
Makefile:149: *** Error: BOARDPATH must be provided.  Stop.

kerry@Kerry-pc MINGW64 ~/Documents/AmbiqSuiteSDK/boards_sfe/common/examples/blinky/gcc ((9c31f07...))
$ make $YOUR_BOARD bootload
Makefile:109: warning: no BOARD specified, will fall back to BOARDPATH for arbitrary bsp locations
Makefile:117: warning: you have not defined COM_PORT. Assuming it is COM4
Makefile:121: warning: you have not defined PYTHON3. assuming it is accessible by 'python3'
Makefile:125: defaulting to 115200 baud for ASB
Makefile:129: defaulting to 921600 baud for SVL
Makefile:134: warning: you have not defined SDKPATH so will continue assuming that the SDK root is at ../../../../..
Makefile:142: warning: you have not defined COMMONPATH so will continue assuming that the COMMON root is at ../../../../common
Makefile:149: *** Error: BOARDPATH must be provided.  Stop.

I've been make ing with sdk 2.2 successfully for a couple of months now...same computer, toolchain, etc.  Followed the Getting started from 
  Then follow these steps

**Comment by kerryeven** [comment]
ok....

defined BOARDPATH line 94 makefile to be:
BOARDPATH		?=../../../.. # Set as the path to the board if not located at ../../..

then followed directions of Getting started but instead of:
    make $YOUR_BOARD bootload_asb
had to use:
    $ make BOARD=$YOUR_BOARD bootload_asb

BOARD= was missing in getting started notes.  Works great now...nice!!

**Comment by kerryeven** [comment]
re-downloaded bsp's from bsp repo and everything worked out of box..no makefile changes

**Comment by kerryeven** [comment]
The Getting Started in the repo and instructions in https://github.com/sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs
are different....no BOARD= in this repo.  Also, seems weird that everything worked when I followed the Install instruct's at BSP repo it works, but not when I first followed these getting started instructs?  Probably user error.

**Comment by oclyke** [comment]
Oops! Yup I accidentally left ```BOARD=``` out of most of the example commands in **Installation** section of the README. I Have corrected that with (8f0271f8578b3d515861fac3ec6178d92f18174b). Are there any other remaining issues? (I just tried following the installation instructions and had success uploading the ble_freertos_tag example)

Thanks for user-testing this stuff! I appreciate the additional perspective.

**Comment by kerryeven** [comment]
You bet.  Blinky working for me very nicely.  Trying to get amdtps to compile now.  Tried 2.3 awhile back and gave up because Ambiq changed some stuff.  Wish me luck...
    On Wednesday, January 29, 2020, 10:30:59 AM EST, Owen <notifications@github.com> wrote:  
 
 
Oops! Yup I accidentally left BOARD= out of most of the example commands in Installation section of the README. I Have corrected that with (8f0271f). Are there any other remaining issues? (I just tried following the installation instructions and had success uploading the ble_freertos_tag example)

Thanks for user-testing this stuff! I appreciate the additional perspective.

**Comment by oclyke** [comment]
Great, thanks. P.s. I've added a section to the README regarding more advanced usage for custom BSP packages.
